### PR TITLE
图床统一更换Github配合jsDelivr

### PR DESCRIPTION
**Pull request by Fangshing87**
图床统一更换Github配合jsDelivr

### CODE REVIEW

**Review by BoxuanZng — COMMENTED** [review]
emm，其实并不需要啊

**Comment by Logic530** [comment]
> emm，其实并不需要啊

有备份避免以后图裂了找不到也可以

**Review by LTCatt — COMMENTED** [review]
目前暂时不需要？现在加载挺正常的……

**Comment by Big-Cake-jpg** [comment]
jsDelivr 备案掉了，用 jsDelivr 进行图片加载可能不稳定（最近更新的使用准则好像不让用来做图床了）

**Comment by WTP016-CN** [comment]
> jsDelivr 备案掉了，用 jsDelivr 进行图片加载可能不稳定（最近更新的使用准则好像不让用来做图床了）

我去官网和 GitHub 项目找了一下 没有找到使用准则 如果你有找到的话麻烦挂出一份原文- -

**Comment by Big-Cake-jpg** [comment]
> > jsDelivr 备案掉了，用 jsDelivr 进行图片加载可能不稳定（最近更新的使用准则好像不让用来做图床了）
> 
> 
> 
> 我去官网和 GitHub 项目找了一下 没有找到使用准则 如果你有找到的话麻烦挂出一份原文- -

Acceptable Use Policy
Effective date: February 17, 2021

Prospect One ("us", "we", or "our") operates the cdn.jsdelivr.net website (the "Service" or "jsDelivr").

By using jsDelivr, you agree to follow this Acceptable Use Policy (the "Policy"). If you are found to be in violation of the Policy at any time, as determined by Prospect One in its sole discretion, we may warn you, prevent you from using our Service, or take any other action we deem appropriate. Please note that we may change our Acceptable Use Policy at any time, and it is your responsibility to keep up-to-date with and adhere to the Policy posted here.

1. Permitted Use

jsDelivr works as a CDN for content already stored on npm, GitHub, and other third-party services. These services are not operated by us, and each of them has its own terms of use. Any content accessed via jsDelivr must conform to the terms of the service from which it was retrieved. For example, when you use jsDelivr as a CDN for GitHub, the content must conform to all GitHub's policies. Additionally, any content accessed via jsDelivr must conform to our own policies as described in this document.

As long as you do not violate our rules:

using jsDelivr is free for both personal and commercial use,
there are no limits on bandwidth or number of requests,
we will provide a reasonable level of support via GitHub issues and email for urgent and private matters.
2. Hard Limits and Restrictions

To maintain the performance and security of our Service, we have various limits and restrictions in place. These may include but are not limited to:

maximum size of a single file,
maximum number of files in a single package,
maximum size of a single package,
blocking of certain file extensions.
When requesting a resource that does not meet these limits, you will get an error response indicating the reason. The limits are set considerably higher than needed for most projects and may be further increased or removed for legitimate projects on request.

3. Soft Limits and Recommendations

These limits are not automatically enforced by our Service, but you agree not to exceed them:

For projects using our GitHub proxy:
We recommend that the number of actively accessed files per repository does not exceed 10 000. If you have considerably more files, a custom proxy endpoint for your project may be a better fit.
The soft limit for the number of files per repository is 100 000.
4. Prohibited Use

The following behavior is prohibited:

Hosting or accessing content that:

contains malware or harmful code in any form,
violates proprietary rights of others,
is sexually explicit,
is potentially illegal in the EU or the USA.
Abusing the service and its resources, or using jsDelivr as a general-purpose file or media hosting service. This includes, for example:

running an image hosting website and using jsDelivr as a storage for all uploaded images,
hosting videos, file backups, or other files in large quantities.
We recognize that there are legitimate projects that consist of a large number of files, and these are not considered abuse. For example: icons packs, apps, or games with a large number of assets.

Trying to bypass our limits or restrictions in any way. We will be happy to remove limits or provide custom solutions for legitimate projects.

5. Additional Restrictions in China

jsDelivr holds an ICP license issued by the Chinese government, which allows us to operate infrastructure directly in Mainland China. To keep this license and allow our Chinese users to benefit from the performance improvements it provides, any content served via our Chinese network must conform to Chinese policies. Content potentially violating Chinese policies may be blocked in China without warning.

6. Limitation of Liability

In no event will the Prospect One and/or jsDelivr entities be liable to you or any third party for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or relating to your access to or use of, or your inability to access or use, the websites and online services or any materials or content on the websites and online services, whether based on warranty, contract, tort (including negligence), statute, or any other legal theory, whether or not the Prospect One and/or jsDelivr entities have been informed of the possibility of such damage.

7. Contact Us

If you have any questions about this Acceptable Use Policy, please contact us:

By email: dak@prospectone.io

**Pull request closed without merging**
